POST http://localhost:3000/api/skills
Content-Type: application/json

{
    "name" : "Typescript"
}

###
GET http://localhost:3000/api/skills

###
PUT http://localhost:3000/api/skills
Content-Type: application/json

{
    "id" : 5,
    "name" : "GoLang"
    }

###
DELETE http://localhost:3000/api/skills
Content-Type: application/json

{
    "id" : 5
}