POST http://localhost:3000/api/wilders
Content-Type: application/json

{
    "name" : "Jane Doe"
}

###
GET http://localhost:3000/api/wilders

###
PUT http://localhost:3000/api/wilders
Content-Type: application/json

{
    "id" : 4,
    "name" : "John Doe"
}

###
PUT http://localhost:3000/api/wilders/addSkill
Content-Type: application/json

{
    "id" : 5,
    "skillName" : "C++"
}

###
DELETE http://localhost:3000/api/wilders
Content-Type: application/json

{
    "id" : 3
}