POST http://localhost:5000/api/wilders
Content-Type: application/json

{
    "name" : "Jane Doe",
    "city" : "CodesVille"
}

###
GET http://localhost:5000/api/wilders

###
PUT http://localhost:5000/api/wilders
Content-Type: application/json

{
    "id" : 1,
    "city" : "Bayonne",
    "description" : "updated description",
    "grades" : [
        {
            "id" : "2",
            "title" : "Python",
            "votes" : 10
        }
    ]
}

###
POST http://localhost:5000/api/wilders/addSkill
Content-Type: application/json

{
    "wilderId" : 1,
    "skillId" : 1,
    "grade": 9
}

###
DELETE http://localhost:5000/api/wilders
Content-Type: application/json

{
    "id" : 2
}